steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bigquery-390709/drzz:$COMMIT_SHA', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bigquery-390709/drzz:$COMMIT_SHA']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'drzz'
      - '--image=gcr.io/bigquery-390709/drzz:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=asia-south1'
